# .gitlab-ci.yml for Chat Application CI/CD

# Define global variables for the pipeline
variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME_VAR: $DOCKER_USERNAME # Reference the CI/CD variable
  DOCKER_PASSWORD_VAR: $DOCKER_PASSWORD # Reference the CI/CD variable
  # IMPORTANT: Replace "swathiraok" below with your actual Docker Hub username.
  DOCKER_IMAGE_BACKEND: swathiraok/chat-backend:latest # Full image name for backend
  DOCKER_IMAGE_FRONTEND: swathiraok/chat-frontend:latest # Full image name for frontend

# Define the stages of your pipeline
stages:
  - build_images
  - push_images

# --- Backend CI/CD Jobs ---

build_backend_image:
  stage: build_images
  image: docker:20.10.24 # Changed image to a specific, stable Docker CLI version
  services:
    - docker:20.10.24-dind # Updated: Using a specific stable Docker in Docker version
  before_script:
    # Login to Docker Hub before building/pushing
    - 'echo "$DOCKER_PASSWORD_VAR" | docker login -u "$DOCKER_USERNAME_VAR" --password-stdin $DOCKER_REGISTRY'
  script:
    - 'echo "Building backend Docker image..."' # Added quotes
    - cd backend # Navigate into the backend directory
    # Added --no-cache and --progress=plain for more verbose build output
    - 'docker build --no-cache --progress=plain -t $DOCKER_IMAGE_BACKEND .'
    - 'echo "Docker build command finished. Listing images:"' # New line for debugging
    - 'docker images' # New line: list images to confirm it was created
    - 'echo "Backend Docker image built: $DOCKER_IMAGE_BACKEND"' # Added quotes
  # Simplified rules to ensure it triggers on every push to 'main'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


push_backend_image:
  stage: push_images
  image: docker:20.10.24 # Changed image to a specific, stable Docker CLI version
  services:
    - docker:20.10.24-dind # Updated: Using a specific stable Docker in Docker version
  before_script:
    - 'echo "$DOCKER_PASSWORD_VAR" | docker login -u "$DOCKER_USERNAME_VAR" --password-stdin $DOCKER_REGISTRY'
  script:
    - 'echo "Pushing backend Docker image..."' # Added quotes
    - docker push $DOCKER_IMAGE_BACKEND # Push the backend image
    - 'echo "Backend Docker image pushed."' # Added quotes
  needs: ["build_backend_image"]
  # Simplified rules to ensure it triggers on every push to 'main'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# --- Frontend CI/CD Jobs ---

build_frontend_image:
  stage: build_images
  image: docker:20.10.24 # Changed image to a specific, stable Docker CLI version
  services:
    - docker:20.10.24-dind # Updated: Using a specific stable Docker in Docker version
  before_script:
    - 'echo "$DOCKER_PASSWORD_VAR" | docker login -u "$DOCKER_USERNAME_VAR" --password-stdin $DOCKER_REGISTRY'
  script:
    - 'echo "Building frontend Docker image..."' # Added quotes
    - cd frontend/chat-frontend # Navigate into the frontend directory
    # Added --no-cache and --progress=plain for more verbose build output
    - 'docker build --no-cache --progress=plain -t $DOCKER_IMAGE_FRONTEND .' # Build the frontend image
    - 'echo "Docker build command finished. Listing images:"' # New line for debugging
    - 'docker images' # New line: list images to confirm it was created
    - 'echo "Frontend Docker image built: $DOCKER_IMAGE_FRONTEND"' # Added quotes
  # Simplified rules to ensure it triggers on every push to 'main'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

push_frontend_image:
  stage: push_images
  image: docker:20.10.24 # Changed image to a specific, stable Docker CLI version
  services:
    - docker:20.10.24-dind # Updated: Using a specific stable Docker in Docker version
  before_script:
    - 'echo "$DOCKER_PASSWORD_VAR" | docker login -u "$DOCKER_USERNAME_VAR" --password-stdin $DOCKER_REGISTRY'
  script:
    - 'echo "Pushing frontend Docker image..."' # Added quotes
    - docker push $DOCKER_IMAGE_FRONTEND # Push the frontend image
    - 'echo "Frontend Docker image pushed."' # Added quotes
  needs: ["build_frontend_image"]
  # Simplified rules to ensure it triggers on every push to 'main'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
