// File: chat/src/main/java/com/example/chat/ChatApplication.java
// This file is usually generated by Spring Initializr. Just ensure its content matches.

package com.example.chat;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication // This annotation marks it as a Spring Boot application.
public class ChatApplication {

    public static void main(String[] args) {
        // This is the entry point of the Spring Boot application.
        // It bootstraps the application and starts the embedded web server.
        SpringApplication.run(ChatApplication.class, args);
    }

}
